@albumId = 60acb00774d5e88524bb3eea
@commentId = 60acaa823eb0d47e5726832d

@songId = 60acb00774d5e88524bb3eec

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGFjYjAwNzc0ZDVlODg1MjRiYjNlZTUiLCJpYXQiOjE2MjE5MzA0OTksImV4cCI6MTYyMTk3MzY5OX0.vxsObUsHJ58j_m5U9p_k8fSbM-ALBo4bcs_CFTFkzvw

GET http://localhost:4000/api/albums


###
GET http://localhost:4000/api/albums/{{albumId}}

###
GET http://localhost:4000/api/albums/{{albumId}}/comments

###
POST http://localhost:4000/api/albums/{{albumId}}/comments
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "text": "This is my comment LOLOLO"
}
###
PUT http://localhost:4000/api/albums/{{albumId}}/comments/{{commentId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "text": "This is my comment."
}
###
DELETE  http://localhost:4000/api/albums/{{albumId}}/comments/{{commentId}}
Content-Type: application/json
Authorization: Bearer {{token}}
###
POST http://localhost:4000/api/albums
Content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "Album6",
  "year": "2010-01-01",
  "lenght": 0,
  "songs": []
}


###
PUT http://localhost:4000/api/albums/{{albumId}}
Content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "Album9",
  "year": "2010-01-01",
  "lenght": 0,
  "songs": []
}

###
DELETE  http://localhost:4000/api/albums/{{albumId}}
Content-type: application/json
Authorization: Bearer {{token}}

###
GET http://localhost:4000/api/albums/{{albumId}}/songs

###
POST http://localhost:4000/api/albums/{{albumId}}/songs

###
DELETE http://localhost:4000/api/albums/{{albumId}}/songs/{{songId}}
Authorization: Bearer {{token}}


###
GET http://localhost:4000/api/playlist


###
GET http://localhost:4000/api/playlist/60acb00874d5e88524bb3ef0

###
GET http://localhost:4000/api/playlist/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "MyPlaylist 1"
}