@albumId = 60abc7ff4b6beb66e32ab0d2
@commentId = 60abbbe1da173f591173dce2

@songId = 60abc8004b6beb66e32ab0d4

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGFiYzdmZjRiNmJlYjY2ZTMyYWIwY2QiLCJpYXQiOjE2MjE4NzIwNDIsImV4cCI6MTYyMTkxNTI0Mn0.c77wnHJG_lEkV58Ab1K2YigTxZLJuhNrTW8KrrxqU2M

GET http://localhost:4000/api/albums


###
GET http://localhost:4000/api/albums/{{albumId}}

###
GET http://localhost:4000/api/albums/{{albumId}}/comments

###
POST http://localhost:4000/api/albums/{{albumId}}/comments
Content-Type: application/json

{
  "text": "This is my comment LOLOLO"
}
###
PUT http://localhost:4000/api/albums/{{albumId}}/comments/{{commentId}}
Content-Type: application/json

{
  "text": "This is my comment. LOL"
}
###
DELETE  http://localhost:4000/api/albums/{{albumId}}/comments/{{commentId}}
Content-Type: application/json

###
POST http://localhost:4000/api/albums
Content-type: application/json

{
  "name": "Album5",
  "year": "2010-01-01",
  "lenght": 0,
  "songs": []
}


###
PUT http://localhost:4000/api/albums/{{albumId}}
Content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "Album9",
  "year": "2010-01-01",
  "lenght": 0,
  "songs": []
}

###
DELETE  http://localhost:4000/api/albums/{{albumId}}
Content-type: application/json


###
GET http://localhost:4000/api/albums/{{albumId}}/songs

###
DELETE http://localhost:4000/api/albums/{{albumId}}/songs/{{songId}}

### USER Register

POST http://localhost:4000/api/register
content-type: application/json

{
  "username": "testuser8",
  "email": "testuser8@testuser",
  "password": "pass",
  "passwordConfirmation": "pass",
  "about": "Something About Me",
  "image": "http://image.com/someimage.jpg"
}

### USER Login
POST http://localhost:4000/api/login
content-type: application/json

{
  "email": "user1@user",
  "password": "pass"
}