@id = 60aba3750aadd753362dfe7c
@commentId = 60aba3750aadd753362dfe7d

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGFiYTM3NDBhYWRkNzUzMzYyZGZlNzUiLCJpYXQiOjE2MjE4NzE3ODUsImV4cCI6MTYyMTkxNDk4NX0.ppXaaSbzEg57ARW9P2CZPKjQeuZQxcgA_vxF0JepG-Q


//All songs index.
GET http://localhost:4000/api/songs


###
//Get a single song.
GET http://localhost:4000/api/songs/{{id}}/


###
//Get all comments for a song.
GET http://localhost:4000/api/songs/{{id}}/comments


###
//Upload a song
POST http://localhost:4000/api/songs/
Authorization: Bearer {{token}}
content-type: application/json

{
  "name": "Awesome New Song",
  "year": "2021"
}


###
//Delete a song
DELETE http://localhost:4000/api/songs/{{id}}/
Authorization: Bearer {{token}}


###
//Edit Song
PUT http://localhost:4000/api/songs/{{id}}/
Authorization: Bearer {{token}}  
content-type: application/json

{
  "name": "This song is from future and edited",
  "year": "2029"
}


###
//Create Comment for a song 
POST  http://localhost:4000/api/songs/{{id}}/comments
Authorization: Bearer {{token}}
content-type: application/json

{
  "text": "NEW to be updated"
}


###
//Update Comment 
PUT http://localhost:4000/api/songs/{{id}}/comments/{{commentId}}
Authorization: Bearer {{token}}
content-type: application/json

{
  "text": "THE COMMENT HAS BEEN UPDATED"
}


###
//Delete comment 
DELETE http://localhost:4000/api/songs/{{id}}/comments/{{commentId}}
Authorization: Bearer {{token}}

